version: "3"
services:
  web:
    build: ./frontend
    volumes:
        - ./frontend:/frontend:rw
        - /frontend/node_modules/
    ports:
      - "8080:8080"
  gateway:
    restart: always
    build: ./services/gateway
    volumes:
        - ./services/gateway:/backend
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - mqtt
  mongo:
    image: mongo
    volumes:
      - ./services/data:/data/db
    ports:
      - "27017:27017"
  mqtt:
    image: toke/mosquitto
    container_name: mqtt
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./services/mqtt/config:/mqtt:ro