version: "3"
services:
  mongo:
    image: mongo
    volumes:
      - ./services/data:/data/db
    ports:
      - "27017:27017"
    logging:
      driver: none
  mqtt:
    image: toke/mosquitto
    container_name: mqtt
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./services/mqtt/config:/mqtt:ro