version: "3"
services:
  web:
    build: ./frontend
    command: npm run serve
    volumes:
        - ./frontend:/frontend:rw
        - /frontend/node_modules/
    ports:
      - "8080:8080"
      - "8888:8888"
  mongo:
    image: mongo
    volumes:
      - ./services/data:/data/db
    ports:
      - "27017:27017"
    logging:
      driver: none
  mqtt:
    image: toke/mosquitto
    container_name: mqtt
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./services/mqtt/config:/mqtt:ro