version: "3"
services:
  gateway:
    restart: always
    build: ./services/gateway
    command: nodemon index.js --exec babel-node
    volumes:
        - ./services/gateway:/app
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    image: mongo
    volumes:
      - ./services/data:/data/db
    ports:
      - "27017:27017"